### ISSUE TITLE
Cannot pass stream to request handler

### ISSUE THREAD

**Issue by numfin** [fox1t/fastify-multer#1]
I want to just pass stream from busboy and handle it with other libs through file.stream. But when i call _handleFile callback, nothing happens.

![image](https://user-images.githubusercontent.com/8134947/67568470-00303f00-f735-11e9-867e-839e88312553.png)

All i found is fastify-multer not calling next() if busboy didnt finish request read. How i can solve this?

**Comment by fox1t** [comment]
Hii @numfin thanks for pointing this out. Can you provide a repro repo here on github? I want to start working on this issue using the same starting point you have.

**Comment by numfin** [comment]
@fox1t sorry i was too busy to look at github notifications -_-
I not remember what happened there, i made my own implementation back there. I dont have source now.
