### ISSUE TITLE
Legacy Content Type Parser function signature

### ISSUE THREAD

**Issue by gjovanov** [fox1t/fastify-multer#12]
Hi there,
After upgrading to fastify `3.0.0+`, we are receiving this error in https://roomler.live using `fastify-multer`:

[FSTDEP003] FastifyDeprecation [FSTDEP003]: You are using the legacy Content Type Parser function signature. Use the one suggested in the documentation instead.

```js
fastify.register(multer.contentParser) // HERE
```

Even though, the app is working and this seems to be only a warning, is this something that can be easily fixed?
Thanks.

**Comment by fox1t** [comment]
Hi! Thanks for reporting this! I am going to take a look on this later today. After the fix, I suppose we are going to need a major version bump here in order to be compatible with fastify >= 3.0.0

**Comment by fox1t** [comment]
Hi. May I ask you to provide a repro repository? I am asking this because when working on this i found even more errors (mainly typescript) and I want to be sure to fix all of them.

**Comment by fox1t** [comment]
Hi again, I've just published version 2.0.0 on npm. Let me know if you still have this warning. :)

**Comment by patrick-entinux** [comment]
@fox1t Hello, I'm not the original poster but I am upgrading fastify and fastify-multer and I have no warning for contentParser.

![image](https://user-images.githubusercontent.com/37786000/87626634-ce01ba00-c767-11ea-97fc-7d56dfdd2b21.png)

**Comment by gjovanov** [comment]
Hey @fox1t ,
sorry for my late reply, yesterday was quite busy day.

After I've upgraded to `2.0.1`, the warning has disappeared. The repro repo is `https://github.com/gjovanov/roomler`. Since everything seems fine, I'm closing this issue.

Thanks again for your quick intervention!
