### ISSUE TITLE
Compilation error in Typesript 4

### ISSUE THREAD

**Issue by lynxtaa** [fox1t/fastify-multer#14]
Using typescript 4 in my app I'm getting this error

```
node_modules/fastify-multer/src/lib/file-appender.ts:87:12 - error TS2790: The operand of a 'delete' operator must be optional.

87     delete placeholder.fieldname
              ~~~~~~~~~~~~~~~~~~~~~

Found 1 error.
```

It's because of https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#operands-for-delete-must-be-optional

**Comment by fox1t** [comment]
Hi, Thanks for reporting this. PRs are welcomed! 

Meanwhile, you can use `"skipLibCheck": true` in your `tsconfig.json` to ignore that issue. Actually, setting it to true is raccomanded: lib types are authered already so checking them again shouldn't be needed and it speeds up your compilation time.

**Comment by lynxtaa** [comment]
Thanks, I didn't know about `skipLibCheck`. I'll make a PR regarding this issue

**Comment by fox1t** [comment]
Fix published on npm!
