### ISSUE TITLE
Unsupported Media Type: multipart/form-data;

### ISSUE THREAD

**Issue by kinothUI** [fox1t/fastify-multer#17]
I'm having a project bootstrapped with fastify-cli using fastify-autoloader for route-registration.
When hitting the route with postman or browser I see the following error:
```
{
    "statusCode": 415,
    "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
    "error": "Unsupported Media Type",
    "message": "Unsupported Media Type: multipart/form-data; boundary=--------------------------692531562187385815595956"
}
``` 

I haven't dug too deep yet but it seems that fastify isn't utilizing multer at all. A replication can be found [here](https://github.com/kinothUI/fastify-multer-error).

Cheers

**Comment by fox1t** [comment]
Hi. You need to register the content parser of the multer plugin. Just add `server.register(multer.contentParser)` somewhere. You can find more info in the README file of this repository.

**Comment by kinothUI** [comment]
What a shame! :X

Thanks for pointing out!

**Comment by fox1t** [comment]
No worries!  💯
