### ISSUE TITLE
Snyk vulnerability in busboy 

### ISSUE THREAD

**Issue by harshagarwal00** [fox1t/fastify-multer#23]
https://snyk.io/test/npm/busboy/0.3.1

Fixed in https://snyk.io/test/npm/busboy/1.6.0

**Comment by harshagarwal00** [comment]
@fox1t ??
why is this PR stuck.. please help https://github.com/fox1t/fastify-multer/pull/20

**Comment by shaileshct09021** [comment]
Thanks @harshagarwal00 for adding this PR. waiting on this one gets merged.

**Comment by fox1t** [comment]
Released as [2.0.3](https://www.npmjs.com/package/fastify-multer/v/2.0.3)
