### ISSUE TITLE
incorrect redirection

### ISSUE THREAD

**Issue by kravetsone** [fox1t/fastify-multer#28]
## Your module is called `fastify-multer` and this link redirects to `multer`

> ![image](https://user-images.githubusercontent.com/57632712/205448574-f7df3bda-5e89-44db-93b0-755244db6c8d.png)

## this leads to

> ![image](https://user-images.githubusercontent.com/57632712/205448678-e3757bef-7025-4a1b-a9e7-52ef24d784ef.png)

## although expected this [url](https://github.com/fox1t/fastify-multer/blob/master/StorageEngine.md)

> ![image](https://user-images.githubusercontent.com/57632712/205448730-4af7be5b-a4bf-401e-a240-57c0df5be700.png)

**Comment by fox1t** [comment]
Thanks. Now it is fixed.
