### ISSUE TITLE
Handler called after fileSize limit thrown

### ISSUE THREAD

**Issue by winstef** [fox1t/fastify-multer#4]
Thanks for the great plugin.

I encountered an issue when I set the fileSize limit option.
when uploading a file that is above the limit, it still executes the Handler function, even though it should just return the error.

Is this because the preHandler is Async and it still executes the handler afterwards?

**Comment by fox1t** [comment]
Hi @winstef, first of all thanks. Secondly can you please provide me a repro repository here on github so I can look into this starting from the same code that generates this behavior?

**Comment by winstef** [comment]
sure, I will try to put one together in the coming days.

**Comment by winstef** [comment]
@fox1t  sorry I wasn't able to replicate it, seems like I had an issue with my handler function.
I have a related question though, when setting the fileSize limit, I would expect the LIMIT_FILE_SIZE error to be returned once Busboy has read the file stream up to that limit and abort uploading the file.

But it seems like the file is actually fully uploaded before getting the LIMIT_FILE_SIZE error back from the api call.

For example, upload with a 1MB limit, and trying with a much bigger file, it still takes a long time before getting the limit file size error message.
 
```javascript
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '/tmp/my-uploads')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now())
  }
})

const limitsUpload = {
  fileSize: 1048576, //1MB
  files: 1
};

const upload = multer({ storage: storage, limits: limitsUpload })
```

**Comment by fox1t** [comment]
I am putting this here for future reference, as this last issue you exposed, need more digging into this package dependencies.

https://github.com/mscdex/busboy/blob/967fce0db075cb02765814db3e322d4f64d33a42/lib/types/multipart.js#L221

https://github.com/fox1t/fastify-multer/blob/18b98ca382b1288d3851a59a2d9e27964ed35c96/src/lib/make-prehandler.ts#L81
