### ISSUE TITLE
Property '[kMultipart]' does not exist on type 'IncomingMessage

### ISSUE THREAD

**Issue by jpmayorga** [fox1t/fastify-multer#5]
Hi i'm using typescript and when i import fastify-multer i have this error

`Property '[kMultipart]' does not exist on type 'IncomingMessage'.
node_modules/fastify-multer/src/lib/content-parser.ts(18,50): error TS6133: 'options' is declared but its value is never read.
node_modules/fastify-multer/src/lib/file-appender.ts(53,13): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
used to index type 'FilesInRequest'.
  No index signature with a parameter of type 'string' was found on type 'FilesInRequest'.
node_modules/fastify-multer/src/lib/file-appender.ts(54,11): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
21:23:03 - File change detected. Starting incremental compilation...

node_modules/fastify-multer/src/lib/content-parser.ts(15,10): error TS7053: Element implicitly has an 'any' type because expression of type 'unique symbol' c
an't be used to index type 'IncomingMessage'.
  Property '[kMultipart]' does not exist on type 'IncomingMessage'.
node_modules/fastify-multer/src/lib/content-parser.ts(18,50): error TS6133: 'options' is declared but its value is never read.
node_modules/fastify-multer/src/lib/file-appender.ts(53,13): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
used to index type 'FilesInRequest'.
  No index signature with a parameter of type 'string' was found on type 'FilesInRequest'.
node_modules/fastify-multer/src/lib/file-appender.ts(54,11): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
used to index type 'FilesInRequest'.
  No index signature with a parameter of type 'string' was found on type 'FilesInRequest'.
node_modules/fastify-multer/src/lib/file-appender.ts(56,11): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
used to index type 'FilesInRequest'.
  No index signature with a parameter of type 'string' was found on type 'FilesInRequest'.
node_modules/fastify-multer/src/lib/file-appender.ts(73,13): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
used to index type 'FilesInRequest'.
  No index signature with a parameter of type 'string' was found on type 'FilesInRequest'.
node_modules/fastify-multer/src/lib/file-appender.ts(74,18): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
used to index type 'FilesInRequest'.
  No index signature with a parameter of type 'string' was found on type 'FilesInRequest'.
node_modules/fastify-multer/src/lib/file-appender.ts(76,23): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be
used to index type 'FilesInRequest'.
  No index signature with a parameter of type 'string' was found on type 'FilesInRequest'.
src/app.ts(37,21): error TS6133: 'req' is declared but its value is never read.`

**Comment by fox1t** [comment]
Hi. Can you please put on GitHub a repository that reproduce this issue? I think that there is some kind of incompatibility between tsconfig.json files. 
As soon as you done, just let me know here and I'll do further investigation.
